artifacts_root: "src/artifacts"

logger:
  name: "trimRag_logger"
  root_dir: "src/artifacts/logs"
  format_logging: "[%(asctime)s - { %(levelname)s } - { %(module)s } - %(message)s]"
  datefmt_logging: "%m/%d/%Y %H:%M:%S"
  log_dir: "src/artifacts/logs"
  name_file_logs: "running_logs.log"

exception:
  error_message: "Error occured in python script name [{file_name}] line number [{line_number}] error message [{error_message}]"
  error_details: None

data_ingestion:
  root_dir: "data"
  image_access_key: ""
  audio_access_key: ""
  text_data:
      text_dir: "data/text"
      query: "machine learning weather prediction"
      max_results: 50
      destination: "data/text"
  audio_data: 
      audio_dir: "data/audio"
      url: "https://freesound.org/apiv2/search/text/" 
      query: "weather"
      max_results: 5
      destination: "data/audio"
  image_data:
      image_dir: "data/image"
      url: "https://api.unsplash.com/search/photos"
      query: "weather"
      max_results: 50
      max_pages: 10
      destination: "data/image"

data_processing:
  root_dir: "src/artifacts/data"
  processed_dir: "processed_data"
  text_data:
      text_dir: "data/text" # Dictionary containing text data
      processed_dir: "processed_data/text"

  audio_data:
      audio_dir: "data/audio" # Dictionary containing audio data
      processed_dir: "processed_data/audio"
  image_data:
      image_dir: "data/image" # Dictionary containing image data
      processed_dir: "processed_data/image"
      image_path: ""
      size: 224
      rotate: 10
      horizontal_flip: False
      rotation: 10
      brightness: 0.2
      contrast: 0.2
      scale: 0.8
      ratio: 0.8
      saturation: 0.2
      hue: 0.1
      format: "JPEG"







