artifacts_root: "src/artifacts"

logger:
  name: "trimRag_logger"
  root_dir: "src/artifacts/logs"
  format_logging: "[%(asctime)s - { %(levelname)s } - { %(module)s } - %(message)s]"
  datefmt_logging: "%m/%d/%Y %H:%M:%S"
  log_dir: "src/artifacts/logs"
  name_file_logs: "running_logs.log"

exception:
  error_message: "Error occured in python script name [{file_name}] line number [{line_number}] error message [{error_message}]"
  error_details: None

data_ingestion:
  root_dir: "data"
  image_access_key: ""
  audio_access_key: ""
  text_data:
      text_dir: "data/text"
      query: "machine learning weather prediction"
      max_results: 50
      destination: "data/text"
  audio_data: 
      audio_dir: "data/audio"
      url: "https://freesound.org/apiv2/search/text/" 
      query: "weather"
      max_results: 5
      destination: "data/audio"
  image_data:
      image_dir: "data/image"
      url: "https://api.unsplash.com/search/photos"
      query: "weather"
      max_results: 50
      max_pages: 10
      destination: "data/image"

data_processing:
  root_dir: "src/artifacts/data"
  processed_dir: "processed_data"
  text_data:
      text_dir: "data/text" # Dictionary containing text data
      processed_dir: "processed_data/text"
      text_path: ""

  audio_data:
      audio_dir: "data/audio" # Dictionary containing audio data
      processed_dir: "processed_data/audio"
      audio_path: ""
      target_sr: 44100
      top_db: 60
      scale: True
      fix: True
      mono: True
      pad_mode: "constant"
      frame_length: 512
      hop_length: 256
      n_steps: 4
      bins_per_octave: 32
      res_type: "kaiser_best"
      rate: 44100
      noise: 0.01
      
  image_data:
      image_dir: "data/image" # Dictionary containing image data
      processed_dir: "processed_data/image"
      image_path: ""
      size: 224
      rotate: 10
      horizontal_flip: False
      rotation: 10
      brightness: 0.2
      contrast: 0.2
      scale: 0.8
      ratio: 0.8
      saturation: 0.2
      hue: 0.1
      format: "JPEG"

embedding:
  root_dir: "src/artifacts/data"
  embedding_dir: "embeddings"
  text_data:
    text_dir: "embeddings/text"
    pretrained_model_name: "bert_base_cased"
    max_length: 512
    batch_size: 32
    device: "gpu"
    return_dict: True
    output_hidden_states: True
    return_tensors: "pt" 
    truncation: True 
    padding: True
    add_special_tokens: True
    return_token_type_ids: False
    return_attention_mask: False
    return_overflowing_tokens: False
    return_special_tokens_mask: False

  image_data:
    image_dir: "embeddings/image"
    pretrained_model_name: "openai/clip-vit-base-patch32"
    device: "gpu"
    output_hidden_states: True 
    output_attentions: True
    return_dict:  True
    revision: "main"
    use_safetensors: False
    ignore_mismatched_sizes: False 
    return_tensors: "pt"
    return_overflowing_tokens: False 
    return_special_tokens_mask: False

  audio_data:
    audio_dir: "embeddings/audio"
    pretrained_model_name: "facebook/wav2vec2-base-960h"
    device: "gpu"
    revision:  "main"
    ignore_mismatched_sizes: False
    return_tensors:   "pt"
    trust_remote_code: False
    n_components: 512

multimodal_embedding:
  root_dir: "src/artifacts/data"
  embedding_dir: "embeddings"
  dropout: 0.1
  num_layers: 3
  
  crossmodal_embedding:  
      dim_hidden: 512
      num_heads: 8
      device: "gpu"
      dropout: 0.1
      batch_first: False
      eps: 1e-6
      bias:  True
      num_layers: 3
      training: True
      inplace:   True

  sharedspace_embedding:
      dim_text: 512
      dim_image:  512
      dim_sound: 512
      dim_shared:  512
      device:  "gpu" 
      eps:  1e-6
      bias:  True








