artifacts_root: "src/artifacts"

logger:
  name: "trimRag_logger"
  root_dir: "src/artifacts/logs"
  format_logging: "[%(asctime)s - { %(levelname)s } - { %(module)s } - %(message)s]"
  datefmt_logging: "%m/%d/%Y %H:%M:%S"
  log_dir: "src/artifacts/logs"
  name_file_logs: "running_logs.log"

exception:
  error_message: "Error occured in python script name [{file_name}] line number [{line_number}] error message [{error_message}]"
  error_details: None

data_ingestion:
  root_dir: "data"
  image_access_key: ""
  audio_access_key: ""
  text_data:
      text_dir: "data/text"
      query: "machine learning weather prediction"
      max_results: 50
      destination: "data/text"
  audio_data: 
      audio_dir: "data/audio"
      url: "https://freesound.org/apiv2/search/text/" 
      query: "weather"
      max_results: 5
      destination: "data/audio"
  image_data:
      image_dir: "data/image"
      url: "https://api.unsplash.com/search/photos"
      query: "weather"
      max_results: 50
      max_pages: 10
      destination: "data/image"

data_processing:
  root_dir: "src/artifacts/data"
  processed_dir: "processed_data"
  text_data:
      text_dir: "data/text" # Dictionary containing text data
      processed_dir: "processed_data/text"
      text_path: ""

  audio_data:
      audio_dir: "data/audio" # Dictionary containing audio data
      processed_dir: "processed_data/audio"
      audio_path: ""
      target_sr: 44100
      top_db: 60
      scale: True
      fix: True
      mono: True
      pad_mode: "constant"
      frame_length: 512
      hop_length: 256
      n_steps: 4
      bins_per_octave: 32
      res_type: "kaiser_best"
      rate: 44100
      noise: 0.01
      
  image_data:
      image_dir: "data/image" # Dictionary containing image data
      processed_dir: "processed_data/image"
      image_path: ""
      size: 224
      rotate: 10
      horizontal_flip: False
      rotation: 10
      brightness: 0.2
      contrast: 0.2
      scale: 0.8
      ratio: 0.8
      saturation: 0.2
      hue: 0.1
      format: "JPEG"

embedding:
  root_dir: "src/artifacts/data"
  embedding_dir: "embeddings"
  device: "cuda:0"
  text_data:
    text_dir: "embeddings/text"
    pretrained_model_name: "bert-base-uncased"
    max_length: 512
    # batch_size: 32
    device: "cuda:0"
    return_dict: True
    output_hidden_states: True
    return_tensors: "pt" 
    do_lower_case: True
    truncation: True 
    padding: "max_length"
    add_special_tokens: True
    return_token_type_ids: False
    return_attention_mask: False
    return_overflowing_tokens: False
    return_special_tokens_mask: False

  image_data:
    image_dir: "embeddings/image"
    pretrained_model_name: "openai/clip-vit-base-patch32"
    device: "cuda:0"
    output_hidden_states: True 
    output_attentions: True
    return_dict:  True
    revision: "main"
    use_safetensors: False
    ignore_mismatched_sizes: False 
    return_tensors: "pt"
    return_overflowing_tokens: False 
    return_special_tokens_mask: False

  audio_data:
    audio_dir: "embeddings/audio"
    pretrained_model_name: "facebook/wav2vec2-base-960h"
    device: "cuda:0"
    revision:  "main"
    ignore_mismatched_sizes: False
    return_tensors:   "pt"
    trust_remote_code: False
    n_components: 512

multimodal_embedding:
  root_dir: "src/artifacts/data"
  embedding_dir: "embeddings"
  dropout: 0.1
  num_layers: 3
  
  crossmodal_embedding:  
      dim_hidden: 512
      num_heads: 8
      device: "cuda:0"
      dropout: 0.1
      batch_first: False
      eps: 1e-6
      bias:  True
      num_layers: 3
      training: True
      inplace:   True

  sharedspace_embedding:
      dim_text: 768
      dim_image:  512
      dim_sound: 768
      dim_shared:  512
      device:  "cuda:0" 
      eps:  0.0001
      bias:  True

retrieval:
  root_dir: "src/artifacts/data"
  retrieval_dir: "retrieval"
  device: "cuda:0"
  fusion_method:
    dropout: 0.1 
    attention_fusion:
      input_dim: 512
      embed_dim:  512
      num_heads: 8
      dropout: 0.1
    modality_aligner:
      input_dim: 512
      output_dim: 512
    weighted_fusion:
      dropout: 0.1
  trimodal_retrieval:
    text_retrieval:
      device: "cuda:0"
    image_retrieval:
      device: "cuda:0"
    audio_retrieval:
      device: "cuda:0"




models:
  root_dir: "src/artifacts/models"
  model_name: "gpt2"
  text_model:
    name_of_model: "bert-base-uncased"
  image_model:
    name_of_model: "openai/clip-vit-base-patch32"
  audio_model:
    name_of_model: "facebook/wav2vec2-base-960h"
prompts:
  root_dir: "src/artifacts/prompts"
  prompts_dir: "prompts"
  variable_name: "history"

post_processing:
  root_dir: "src/artifacts/generation"
  folder_name: "generation"
  temperature: 0.0
  verbose: True
  frequency_penalty: 0.0
  max_tokens: 128
  model_cohere: "rerank-english-v3.0" 

generation:
  root_dir: "src/artifacts/generation"
  folder_name: "generation"
  system_str: "System: You are an assistant robot the masterest about weather and climate field in the world. "
  # Context regarding weather topic such as lighting, rain, snow, etc suitable for rag chain generation.
  context: "Lighting, rain, snow, etc. suitable for rag chain generation. "






