from src.trim_rag.config.arguments_config import (
    LoggerArgumentsConfig,
    ExceptionArgumentsConfig,
    DataIngestionArgumentsConfig,
    TextDataIngestionArgumentsConfig,
    ImageDataIngestionArgumentsConfig,
    AudioDataIngestionArgumentsConfig,
    # ArgumentsConfig
    TextDataTransformArgumentsConfig,
    AudioDataTransformArgumentsConfig,
    ImageDataTransformArgumentsConfig,
    DataTransformationArgumentsConfig,
    TextEmbeddingArgumentsConfig,
    ImageEmbeddingArgumentsConfig,
    AudioEmbeddingArgumentsConfig,
    EmbeddingArgumentsConfig,
    MultimodalEmbeddingArgumentsConfig,
    SharedEmbeddingSpaceArgumentsConfig,
    CrossModalEmbeddingArgumentsConfig,
    QdrantVectorDBArgumentsConfig,
    TextDataVectorDBArgumentsConfig,
    ImageDataVectorDBArgumentsConfig,
    AudioDataVectorDBArgumentsConfig,
    TextPrepareDataQdrantArgumentsConfig,
    ImagePrepareDataQdrantArgumentsConfig,
    AudioPrepareDataQdrantArgumentsConfig,
    PrepareDataQdrantArgumentsConfig,
    MultiModelsArgumentsConfig,
    TextModelArgumentsConfig,
    ImageModelArgumentsConfig,
    AudioModelArgumentsConfig,
    PromptFlowsArgumentsConfig,
    PostProcessingArgumentsConfig,
    MultimodalGenerationArgumentsConfig,
    # MultimodalWithMemoriesArgumentsConfig,
    TriModalRetrievalArgumentsConfig,
    ModalityAlignerArgumentsConfig,
    FusionMechanismArgumentsConfig,
    AttentionFusionArgumentsConfig,
    TextRetrievalArgumentsConfig,
    ImageRetrievalArgumentsConfig,
    AudioRetrievalArgumentsConfig,
    WeightedFusionArgumentsConfig,
    TrimodalRetrievalPipelineArgumentsConfig,
    ModalityAlignerArgumentsConfig,
    MultimodalGenerationPipelineArgumentsConfig,
)
from src.trim_rag.config.manager_config import ConfiguarationManager
